name: Greeting

on: [pull_request_target, issues]
jobs:
  greeting:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/github-script@v3
      with:

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating issue, please tell us the issue you found 'please be detail' Thank you"
        pr-message: "Thank you for the pull request, we will review changes to see if a merge is warranted. Thank you."
