on: 
  pull_request:
    types: [opened]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "Thank you for Pull request, we will review it when time permits. Thank you!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
