name: Greeting

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Post greeting message
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueComment = `Thank you for creating issue, please tell us the issue you found 'please be detail' Thank you`;
          const prComment = `Thank you for the pull request, we will review changes to see if a merge is warranted. Thank you.`;
  
          const message = github.event.pull_request ? prComment : issueComment;
  
          github.issues.createComment({
            issue_number: github.event.issue.number,
            owner: github.repository.owner.login,
            repo: github.repository.name,
            body: message
          });
