name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '38 6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to no recent activity. If you are still working on this issue, please provide an update to avoid closure.'
        stale-pr-message: 'This pull request has been marked as stale due to no recent activity. If you are still working on this pull request, please provide an update to avoid closure.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-until-stale: 1
        close-issues-after-days-stale: 2
        close-prs-after-days-stale: 2
