on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install iverilog
        sudo apt-get install verilator

    - name: Build and run simulation
      run: |
        iverilog -o output.vvp ClockDivider.v tb_clock_divider.v
        vvp output.vvp > output.txt
      working-directory: ${{ github.workspace }}

    - name: Save output
      uses: actions/upload-artifact@v2
      with:
        name: simulation-output
        path: output.txt
