on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install iverilog
        sudo apt-get install verilator

    - name: Set permissions
      run: |
        set -x
        chmod +x build/sh
        chmod +x ./ClockDivider.v

    - name: Build application
      run: |
        set -x
        ./build/sh

    - name: Run simulation
      run: |
        set -x
        iverilog -o ClockDivider.vvp ClockDivider.v
        vvp ClockDivider.vvp
        echo "Dump VCD"
        echo "0\nrun\nquit" | gtkwave dump.vcd
        echo "Save simulation results to output.txt"
        pwd
        tee output.txt < dump.vcd

    - name: Compile Verilog files
      run: |
        set -x
        iverilog -o ClockDivider.out ./ClockDivider.v

    - name: Run simulation
      run: |
        set -x
        vvp ClockDivider.out

    - name: Finish
      run: |
        set -x
        echo "Script has finished running."
