on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog
        sudo apt-get install -y verilator

    - name: Build Application using Icarus Verilog
      run: |
        iverilog -o ClockDivider.vvp ClockDivider.v

    - name: Run simulation with VVP
      run: |
        vvp ClockDivider.vvp

    - name: Create output file
      run: |
        cat dump.vcd > output.txt
