name: Verilog Build and Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog
        sudo apt-get install -y gtkwave

    - name: Set executable permission on script file
      run: |
        chmod +x build/sh
        chmod +x ClockDivider.v

    - name: Build Application using script
      run: ./build/sh

    - name: Run iverilog
      run: iverilog -o ClockDivider.vvp ClockDivider.v

    - name: Run simulation
      run: vvp ClockDivider.vvp

    - name: Dump VCD
      run: echo "0\nrun\nquit" | gtkwave dump.vcd

    - name: Save simulation results to output.txt
      run: cp dump.vcd output.txt

    - name: Print completion message
      run: echo "Script has finished running."
