name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install iverilog
        sudo apt-get install verilator

    - name: Set executable permission on script file
      run: |
        chmod +x build/sh

    - name: Run, Build Application using script
      run: |
        ./build/sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
